# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- bash: |
    wget http://curl.haxx.se/download/curl-7.57.0.tar.gz
    tar -xvf curl-7.52.1.tar.gz
    cd curl-7*
    ./configure
    make
    sudo make install

  displayName: "Testing Curl"


